ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        two_d_mode: true

# Whether to broadcast the transformation over the /tf topic. Defaults to true if unspecified.
        publish_tf: false

        # map_frame: map            # Defaults to "map" if unspecified
        odom_frame: odom            # Defaults to "odom" if unspecified
        base_link_frame: base_link  # Defaults to "base_link" if unspecified
        world_frame: odom           # Defaults to the value of odom_frame if unspecified

        odom0: odom0
        # xyz pos.
        # rpy angle
        # xyz vel
        # rpy vel
        # xyz accel.
        odom0_config: [false, false, false,
                       false, false, true,
                       true,  true,  false,
                       false, false, true,
                       false, false, false]
        odom0_queue_size: 10

        imu0: imu0
        imu0_config: [false, false, false,
                      false, false, true,
                      false, false, false,
                      false, false, true,
                      false, false, false]
        imu0_queue_size: 10

        control_config: [true, false, false, false, false, true]
        acceleration_limits: [0.22, 0.0, 0.0, 0.0, 0.0, 2.8]
        dcceleration_limits: [0.22, 0.0, 0.0, 0.0, 0.0, 2.8]
